Data exploration file just to have a looksy before making anything snazzy

Imports:

In [1]:
import pandas as pd

Get the data:

In [3]:
df = pd.read_csv('https://query.data.world/s/oixb7uoaaueo7atplhxjtp4hjo5huq',encoding_errors="ignore")

Ideas from the key and all that sorta stuff
 - so currently each contains an amount about themselves and others, so we need to reconnect things 
 - could look at how accurate are people's opinions of themselves
 - could generate profiles of who gets who 
 - can predict based on who you are who you would like
 - can predict dating prospects 
 
Note: each line refers to one person /w one partner
 - ie. theres a lot of essentially duplicated stuff together
 - so we may want to build a more funky data structure

Notes from the key

 - iid - unique subject number
 - gender - Female = 0, male = 1

 - attN_3 (from after they've had matches)
 - attN_2 (from before they've had matches but after event)
 - attN_1 (from before event)
 - attN_s (from half way through)

 - att1_N - what what do you look for in the opposite sex (either wave 6-9 1-10; wave 1-5/10-21 or 1-100) need to handle this (can check based on dataset)
 - att2_N - what you think opposite sex looks for (awful 1-10 great in _3) (total pts in _2) (either wave 6-9 1-10; wave 1-5/10-21 or 1-100 in _1)
 - att3_N - your opinions of yourself (awful 1-10 great)
 - att4_N - what do you think your sex look for (awful 1-10 great in _3) (total pts in _2) (either wave 6-9 1-10; wave 10-21 or 1-100)
 - att5_N - how you think others percieve you (awful 1-10 great) 
 - att6_N - 
 - att7_N - how important you felt things were (total 100 pts across) <- convert to %

 - satis_2 - how statisfied were you w/ people you met (not sat1-10 sat)

 - date_3 - have you been on a date with any match
 - numdat_3 - how many matches have you been on a date with
 - num_in_3 - how many dates ^

 - you_call - how many have you contacted to set up a date
 - them_cal - how many have contacted you to set up a date

 - exphappy - how happy do you expect to be w/ peeps (1-10)
 - expnum - out of 20 how many do you expect to be interested in you 

 - [activity] - how interested are you in an activity (1-10)
 - career_c - coded inteded career 
        1= Lawyer 
        2= Academic/Research 
        3= Psychologist 
        4= Doctor/Medicine 
        5=Engineer 
        6= Creative Arts/Entertainment 
        7= Banking/Consulting/Finance/Marketing/Business/CEO/Entrepreneur/Admin 
        8= Real Estate 
        9= International/Humanitarian Affairs 
        10= Undecided 
        11=Social Work
        12=Speech Pathology
        13=Politics
        14=Pro sports/Athletics
        15=Other
        16=Journalism
        17=Architecture
 - go_out - how often you go out (not necessarily on dates)
        Several times a week=1
        Twice a week=2
        Once a week=3
        Twice a month=4
        Once a month=5
        Several times a year=6
        Almost never=7
 - dates - how frequently do you go on dates
    	Several times a week=1
        Twice a week=2
        Once a week=3
        Twice a month=4
        Once a month=5
        Several times a year=6
        Almost never=7
 - goal - goal in the event [probably not interesting]
        Seemed like a fun night out=1
        To meet new people=2
        To get a date=3
        Looking for a serious relationship=4
        To say I did it=5
        Other=6
 - income - $ median household income based on zip code (if nan, abroad or not entered)
 - zipcode - what it says on the tin
 - imprelig - how important is matching religious background (1,10)
 - imprace - how important is matching racia.l/ethnic bakground (1,10)
 - tuition - $ tuition based on undergrad
 - undergra - where they did their undergrad (incorrectly labelled)
 - field_cd - field of study coded 
 - age - what it says on the tin

 - pid - partner's iid 
 - age_o - age of partner
 - pf_o_att - preference of partner at time 1
 - dec_o - decision of partner at end of the night
 - attr_o - rating by partner of person at end of the night per attribute

 - int_corr - correlation between interests

 - match - 1 yes; 0 no



 [not interesting]
 - length
 - numdat_2
 - career - field of study, but we want to use the coded version
 - from - don't want to be too specific for america 
 - race - this is probably gonna be more US specific so as above; plus obvs a bit sensitive so lets veeer away from this
 - race_o - race of partner
 - field - field of study, but we want to use the coded version
 - pos - station N when met partner
 - positin1 - station N where started
 - order - N of date when met partner
 - partner - partner's id 
 - round -N of people that met in wave 
 - condtn - 1 limited choice, 2 extensive choice - this is gonna be an awkward confounding variable

In [5]:
#checking exact headers
df.keys()

Index(['iid', 'id', 'gender', 'idg', 'condtn', 'wave', 'round', 'position',
       'positin1', 'order',
       ...
       'attr3_3', 'sinc3_3', 'intel3_3', 'fun3_3', 'amb3_3', 'attr5_3',
       'sinc5_3', 'intel5_3', 'fun5_3', 'amb5_3'],
      dtype='object', length=195)

In [13]:
#checking sorting
df.sort_values(by=["pid"],inplace=True)
df

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
150,16,6.0,1,12,1,1,10,7,NaN,6,...,6.0,6.0,8.0,8.0,8.0,NaN,NaN,NaN,NaN,NaN
110,12,2.0,1,4,1,1,10,7,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,13,3.0,1,6,1,1,10,7,NaN,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,14,4.0,1,8,1,1,10,7,NaN,5,...,9.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN
140,15,5.0,1,10,1,1,10,7,NaN,7,...,7.0,7.0,9.0,7.0,9.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1805,127,6.0,1,12,1,5,10,4,NaN,7,...,8.0,8.0,8.0,8.0,8.0,NaN,NaN,NaN,NaN,NaN
1815,128,7.0,1,14,1,5,10,4,NaN,9,...,9.0,8.0,9.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN
1825,129,8.0,1,15,1,5,10,4,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1835,130,9.0,1,16,1,5,10,4,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1845,131,10.0,1,18,1,5,10,4,NaN,4,...,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN

In [14]:
#checking calc of emergency breakout values
df["pid"].max(numeric_only=True)

552.0

In [17]:
#checking if we have nans in pid column
Count = df.count(numeric_only=True)
#10 more numerric values in iid than pid :/

In [20]:
#checking the attributes used don't have any of the
#sum to 100 stuff which some waves show
suffix = ["3_1","3_s","3_2","3_3","_o"]
for s in suffix:
    print(df[f"attr{s}"].max())

10.0
10.0
10.0
12.0
10.5

So from that 12, some people clearly can't follow instructions, checking the documentation this was never asked for... so I'm just gonna leave it in because if we're gonna do some sort of discrete corrolation analysis anyway then it won't matter as it'll just be ranked high and in a way it does give information to a persons opinion of themself...

In [3]:
#checking to see if we can really easily merge dicts
endDict = {}
dictA={"a":1,"b":2,"c":3}
dictB={"a":3,"d":4,"e":5}
endDict.update(dictA)
endDict.update(dictB)
#cool so update works but will overwrite over things so we need to make sure they keys are unique

In [2]:
#checking to see dict sorting
#now normally a dict hasn't got anorder, but actually in python it does, so we can actually sort one
dict = {"a":5,"b":3,"c":6,"d":5,"e":10}
print(sorted(dict, key=dict.get, reverse=True))
for a in sorted(dict, key=dict.get, reverse=True):
    print(a)

['e', 'c', 'a', 'd', 'b']
e
c
a
d
b